### ISSUE TITLE
askNatureImage wrapper has keywords twice

### ISSUE THREAD

**Issue by keithkade** [ecologylab/BigSemanticsWrapperRepository#36]
http://ecologylab.net/research/bigsemantics/MICE/index.html?url=http://www.asknature.org/media/image/192

I think it is due to both rich_document and this wrapper having keyword scalars. One should probably overwrite the other

**Comment by eakellogg** [comment]
I fixed that issue, but the regex for various fields isn't working.  I'm assuming that is from some update to how we extract things.

**Comment by keithkade** [comment]
pushed. needed to use <regex_op>
