### ISSUE TITLE
imdb actor

### ISSUE THREAD

**Issue by andru1d** [ecologylab/BigSemanticsWrapperRepository#44]
can't see movies when expanding actor :(

**Comment by keithkade** [comment]
Do you mean the images? I don't think I'm seeing the problem

![imdbmicestatus](https://cloud.githubusercontent.com/assets/2426829/7123540/6f9bd2c6-e1e8-11e4-8b9a-da1d89e8603b.png)

**Comment by andru1d** [comment]
i mean actor credits within a movie.

On Mon, Apr 13, 2015 at 2:25 PM, Kade Keith <notifications@github.com>
wrote:

> Do you mean the images? I don't think I'm seeing the problem
>
> [image: imdbmicestatus]
> <https://cloud.githubusercontent.com/assets/2426829/7123540/6f9bd2c6-e1e8-11e4-8b9a-da1d89e8603b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ecologylab/BigSemanticsWrapperRepository/issues/44#issuecomment-92469322>
> .
>



-- 
andruid kerne, ph.d.
director, interface ecology lab
associate professor, department of computer science and engineering
texas a&m university                   979.862.3684 fax
college station, tx 77843-3112       http://ecologylab.net

http://facebook.com/ecologylab

Interfaces are the multidimensional border zones through which the
interdependent relationships of people, activities, codes, components,
and systems are constituted. Interface ecology investigates the
dynamic interactions of media, cultures, and disciplines that
flow through interfaces.

**Comment by keithkade** [comment]
As in what character each actor played?

**Comment by andru1d** [comment]
seems to be o.k. now.

nevermind. thanks.

andruid

On Wed, Apr 15, 2015 at 2:44 PM, Kade Keith <notifications@github.com>
wrote:

> As in what character each actor played?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ecologylab/BigSemanticsWrapperRepository/issues/44#issuecomment-93544942>
> .
>



-- 
andruid kerne, ph.d.
director, interface ecology lab
associate professor, department of computer science and engineering
texas a&m university                   979.862.3684 fax
college station, tx 77843-3112       http://ecologylab.net

http://facebook.com/ecologylab

Interfaces are the multidimensional border zones through which the
interdependent relationships of people, activities, codes, components,
and systems are constituted. Interface ecology investigates the
dynamic interactions of media, cultures, and disciplines that
flow through interfaces.
